# Generated by Django 2.1.2 on 2018-10-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='신청인 이름')),
                ('telephone', models.TextField(verbose_name='연락처')),
                ('address', models.TextField(verbose_name='주소')),
                ('email', models.TextField(verbose_name='이메일')),
                ('content', models.TextField(verbose_name='신청내용')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='신청인 이름')),
                ('telephone', models.TextField(verbose_name='연락처')),
                ('address', models.TextField(verbose_name='주소')),
                ('email', models.TextField(verbose_name='이메일')),
                ('content', models.TextField(verbose_name='신청내용')),
            ],
        ),
    ]
