# Generated by Django 2.1.2 on 2018-10-09 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mento',
            options={'verbose_name': '멘토', 'verbose_name_plural': '멘토신청'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': '자원봉사', 'verbose_name_plural': '자원봉사신청'},
        ),
        migrations.AddField(
            model_name='mento',
            name='created_a',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='신청일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='created_a',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='신청일'),
            preserve_default=False,
        ),
    ]
