# Generated by Django 2.1.2 on 2018-10-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20181009_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mento',
            options={'verbose_name': '멘토', 'verbose_name_plural': '멘토신청인'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': '자원봉사', 'verbose_name_plural': '자원봉사신청인'},
        ),
        migrations.RenameField(
            model_name='mento',
            old_name='created_a',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='created_a',
            new_name='created_at',
        ),
    ]
