# Generated by Django 2.0.7 on 2018-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_workexp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mento',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='workexp',
            name='address',
        ),
        migrations.AddField(
            model_name='mento',
            name='info_agree',
            field=models.BooleanField(default=True, verbose_name='개인정보 동의'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mento',
            name='schoolinfo',
            field=models.TextField(default=True, verbose_name='학교 및 학년'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='info_agree',
            field=models.BooleanField(default=True, verbose_name='개인정보 동의'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='schoolinfo',
            field=models.TextField(default=True, verbose_name='학교 및 학년'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexp',
            name='info_agree',
            field=models.BooleanField(default=True, verbose_name='개인정보 동의'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexp',
            name='schoolinfo',
            field=models.TextField(default=True, verbose_name='학교 및 학년'),
            preserve_default=False,
        ),
    ]
