# Generated by Django 2.1.2 on 2018-10-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='사진명')),
                ('classify', models.CharField(choices=[('inside', '센터 내 프로그램'), ('school', '학교 진행 프로그램'), ('outside', '외부 프로그램'), ('others', '기타')], max_length=10, verbose_name='성별')),
                ('photo', models.ImageField(upload_to='Gallery/%Y/%m/%d', verbose_name='갤러리 사진')),
            ],
            options={
                'verbose_name': '메인사진첩',
                'verbose_name_plural': '메인사진첩',
            },
        ),
    ]
