# Generated by Django 2.1.2 on 2018-10-10 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20181010_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='날짜'),
            preserve_default=False,
        ),
    ]
