# Generated by Django 2.1.2 on 2018-10-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='end_schdule',
            new_name='end_schedule',
        ),
    ]
