# Generated by Django 2.1.2 on 2018-10-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20181009_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programsignup',
            name='contact',
            field=models.CharField(max_length=256, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='programsignup',
            name='guardian_contact',
            field=models.CharField(max_length=256, verbose_name='보호자 연락처'),
        ),
    ]
