# Generated by Django 2.1.2 on 2018-11-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20181009_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsignup',
            name='email',
            field=models.CharField(default='warak@warak.or.kr', max_length=256, verbose_name='이메일'),
        ),
    ]
