# Generated by Django 2.0.7 on 2018-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_program_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='volunteer_max',
            field=models.IntegerField(default=0, verbose_name='최대지원자'),
        ),
    ]
