# Generated by Django 2.0.7 on 2018-12-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_program_volunteer_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsignup',
            name='email',
            field=models.CharField(default='maple@naver.com', max_length=20, verbose_name='이메일'),
        ),
    ]
