# Generated by Django 2.0.7 on 2018-12-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_programsignup_email'),
        ('program', '0008_programsignup_email'),
    ]

    operations = [
    ]
