# Generated by Django 2.1.2 on 2018-10-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='위치')),
                ('photo', models.ImageField(upload_to='mainPhoto/', verbose_name='메인 사진')),
            ],
            options={
                'verbose_name': '메인사진첩',
                'verbose_name_plural': '메인사진첩',
            },
        ),
    ]
