# Generated by Django 2.1.2 on 2018-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('position', models.CharField(max_length=20, verbose_name='직위')),
                ('career', models.TextField(blank=True, null=True, verbose_name='경력')),
                ('photo', models.ImageField(upload_to='Employee/', verbose_name='사진')),
            ],
            options={
                'verbose_name': '직원',
                'verbose_name_plural': '직원',
            },
        ),
    ]
