# Generated by Django 2.1.2 on 2018-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181026_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('image', models.ImageField(upload_to='popup/%Y/%m/%d', verbose_name='사진')),
            ],
            options={
                'verbose_name': '팝업창 수정',
                'verbose_name_plural': '팝업창 수정',
            },
        ),
    ]
