# Generated by Django 2.1.2 on 2018-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='제목'),
        ),
    ]
