# Generated by Django 2.1.2 on 2018-10-27 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_popup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
