# Generated by Django 2.1.2 on 2018-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20181015_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default=1, upload_to='notice/%Y/%m/%d', verbose_name='사진'),
            preserve_default=False,
        ),
    ]
