# Generated by Django 2.1.2 on 2018-10-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice/%Y/%m/%d', verbose_name='사진'),
        ),
    ]
